gui:
  showRandomTip: false
  showCommandLog: false
  showFileTree: false
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
disableStartupPopups: true
notARepository: 'skip'
git:
  branchLogCmd: "git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(blue)<%an>%Creset' --abbrev-commit"
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editPreset: 'nvim'
