[mgr]
prepend_keymap = [
  { on = '-', run = 'leave', desc = 'Go back to the parent directory' },
  { on = '<Enter>', run = 'plugin smart-enter', desc = 'Enter child dir or open file' },
  { on = 'l', run = 'plugin smart-enter', desc = 'Enter child dir or open file' },
  { on = 'e', run = "shell 'nvim $@' --block", desc = "Open selected files in neovim" },
]

[input]
prepend_keymap = [
  { on = '<Esc>', run = 'close', desc = 'Cancel input' },
]
